version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"


  - package-ecosystem: npm
    directory: /test/fixtures/getTarballComposition/two
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /test/fixtures/scanPackage/caseone
    schedule:
      interval: daily
