name: Changesets
on:
  push:
    branches:
      - main
env:
  CI: true

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build monorepo
        run: npm run build

      - name: Update and publish versions
        uses: changesets/action@e0538e686673de0265c8a3e2904b8c76beaa43fd # v1.5.2
        with:
          version: npm run ci:version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: npm run ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
